const columns = [
  { name: 'ID', uid: 'id', sortable: true },
  { name: 'Employee', uid: 'name' },
  { name: 'Course', uid: 'course' },
  { name: 'Price', uid: 'price', sortable: true },
  { name: 'Date', uid: 'date', sortable: true },
  { name: 'AGE', uid: 'age', sortable: true },
  { name: 'ROLE', uid: 'role', sortable: true },
  { name: 'TEAM', uid: 'team' },
  { name: 'EMAIL', uid: 'email' },
  { name: 'STATUS', uid: 'status', sortable: true },
  { name: '', uid: 'actions' },
];

const statusOptions = [
  { name: 'Active', uid: 'active' },
  { name: 'Paused', uid: 'paused' },
  { name: 'Vacation', uid: 'vacation' },
];

const users = [
  {
    id: 1,
    name: 'Tony Reichert',
    role: 'CEO',
    team: 'Management',
    course: 'The Complete Web Developer Course 3.0',
    price: 90,
    date: 'Dec 08 2023 10:00:00 AM',
    status: 'active',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'tony.reichert@example.com',
  },
  {
    id: 2,
    name: 'Zoey Lang',
    role: 'Tech Lead',
    team: 'Development',
    course: 'From start-up to scale-up',
    price: 145,
    date: 'Dec 19 2023 10:00:00 AM',
    status: 'paused',
    age: '25',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    email: 'zoey.lang@example.com',
  },
  {
    id: 3,
    name: 'Jane Fisher',
    role: 'Product owner',
    team: 'Development',
    course: 'Python for beginners',
    price: 145,
    date: 'Dec 10 2020 10:00:00 AM',
    status: 'active',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
    email: 'jane.fisher@example.com',
  },
  {
    id: 4,
    name: 'William Howard',
    role: 'Product owner',
    team: 'Marketing',
    course: 'Masterclass: Art, Sketching, Drawing',
    price: 120,
    date: 'Nov 9 2022 10:00:00 AM',
    status: 'vacation',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
    email: 'william.howard@example.com',
  },
  {
    id: 5,
    name: 'Kristen Copper',
    price: 135,
    date: 'Mar 8 2023 10:00:00 AM',
    role: 'S. Manager',
    team: 'Sales',
    course: 'HR for dummies',
    status: 'active',
    age: '24',
    avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
    email: 'kristen.cooper@example.com',
  },
  {
    id: 6,
    name: 'Brian Kim',
    price: 145,
    date: 'Jan 8 2023 10:00:00 AM',
    role: 'P. Manager',
    team: 'Management',
    course: 'Practical Project Management',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'brian.kim@example.com',
    status: 'Active',
  },
  {
    id: 7,
    name: 'Michael Hunt',
    price: 145,
    date: 'Mar 7 2023 10:00:00 AM',
    role: 'Designer',
    team: 'Design',
    course: 'HR for dummies',
    status: 'paused',
    age: '27',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29027007d',
    email: 'michael.hunt@example.com',
  },
  {
    id: 8,
    name: 'Samantha Brooks',
    price: 155,
    date: 'Mar 6 2023 10:00:00 AM',
    role: 'HR Manager',
    team: 'HR',
    course: 'Masterclass: Art, Sketching, Drawing',
    status: 'active',
    age: '31',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e27027008d',
    email: 'samantha.brooks@example.com',
  },
  {
    id: 9,
    name: 'Frank Harrison',
    role: 'F. Manager',
    team: 'Finance',
    course: 'HR for dummies',
    price: 159,
    date: 'May 5 2023 10:00:00 AM',
    status: 'vacation',
    age: '33',
    avatar: 'https://i.pravatar.cc/150?img=4',
    email: 'frank.harrison@example.com',
  },
  {
    id: 10,
    name: 'Emma Adams',
    price: 199,
    date: 'July 4 2023 10:00:00 AM',
    role: 'Ops Manager',
    team: 'Operations',
    course: 'Masterclass: Art, Sketching, Drawing',
    status: 'active',
    age: '35',
    avatar: 'https://i.pravatar.cc/150?img=5',
    email: 'emma.adams@example.com',
  },
  {
    id: 11,
    name: 'Brandon Stevens',
    price: 249,
    date: 'Apr 3 2023 10:00:00 AM',
    role: 'Jr. Dev',
    team: 'Development',
    course: 'Masterclass: Art, Sketching, Drawing',
    status: 'active',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?img=8',
    email: 'brandon.stevens@example.com',
  },
  {
    id: 12,
    name: 'Megan Richards',
    role: 'P. Manager',
    team: 'Product',
    price: 229,
    date: 'June 2 2023 10:00:00 AM',
    course: 'HR for dummies',
    status: 'paused',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?img=10',
    email: 'megan.richards@example.com',
  },
  {
    id: 13,
    name: 'Oliver Scott',
    role: 'S. Manager',
    price: 165,
    date: 'Feb 1 2023 10:00:00 AM',
    team: 'Security',
    course: 'Masterclass: Art, Sketching, Drawing',
    status: 'active',
    age: '37',
    avatar: 'https://i.pravatar.cc/150?img=12',
    email: 'oliver.scott@example.com',
  },
  {
    id: 14,
    name: 'Grace Allen',
    role: 'M. Specialist',
    price: 188,
    date: 'Feb 15 2023 10:00:00 AM',
    team: 'Marketing',
    course: 'HR for dummies',
    status: 'active',
    age: '30',
    avatar: 'https://i.pravatar.cc/150?img=16',
    email: 'grace.allen@example.com',
  },
  {
    id: 15,
    name: 'Noah Carter',
    role: 'IT Specialist',
    price: 200,
    date: 'Jan 16 2023 10:00:00 AM',
    team: 'I. Technology',
    status: 'paused',
    course: 'Practical Project Management',
    age: '31',
    avatar: 'https://i.pravatar.cc/150?img=15',
    email: 'noah.carter@example.com',
  },
  {
    id: 16,
    name: 'Ava Perez',
    price: 250,
    date: 'Nov 20 2023 10:00:00 AM',
    role: 'Manager',
    team: 'Sales',
    course: 'HR for dummies',
    status: 'active',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?img=20',
    email: 'ava.perez@example.com',
  },
  {
    id: 17,
    name: 'Liam Johnson',
    role: 'Data Analyst',
    team: 'Analysis',
    status: 'active',
    price: 300,
    date: 'Dec 17 2023 10:00:00 AM',
    course: 'HR for dummies',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?img=33',
    email: 'liam.johnson@example.com',
  },
];

export { columns, users, statusOptions };
